### ISSUE TITLE
how to convert yolov8 custom model to tflite format

### ISSUE THREAD

**Issue by chaukamm** [vladiH/flutter_vision#51]
i have tried convert .pt file to .onnx file, then convert to .pb file, finally .tflite file. but it seems didnt work

**Comment by LucasCarvalhoPAVIC** [comment]
I used this code in google colab to convert:

%pip install ultralytics
from ultralytics import YOLO
model = YOLO(r"/content/best.pt")
model.export(format="tflite")

**Comment by chaukamm** [comment]
Ultralytics YOLOv8.0.151  Python-3.9.13 torch-2.5.1+cu118

i tried this to train model and it generate best.pt and i export to tflite
when i try to load the model in flutter, it shows this
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(100, Error on load Yolov5 model, java.io.FileNotFoundException: flutter_assets/front2_new4.tflite
E/flutter ( 7059): 	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
E/flutter ( 7059): 	at android.content.res.AssetManager.openFd(AssetManager.java:986)
E/flutter ( 7059): 	at com.vladih.computer_vision.flutter_vision.models.Yolo.initialize_model(Yolo.java:86)
E/flutter ( 7059): 	at com.vladih.computer_vision.flutter_vision.FlutterVisionPlugin.load_yolo_model(FlutterVisionPlugin.java:225)
E/flutter ( 7059): 	at com.vladih.computer_vision.flutter_vision.FlutterVisionPlugin.onMethodCall(FlutterVisionPlugin.java:99)
E/flutter ( 7059): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 7059): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 7059): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 7059): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 7059): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 7059): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7059): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter ( 7059): 	at android.os.Looper.loop(Looper.java:313)
E/flutter ( 7059): 	at android.app.ActivityThread.main(ActivityThread.java:8810)
E/flutter ( 7059): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7059): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/flutter ( 7059): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/flutter ( 7059): , null)
E/flutter ( 7059): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 7059): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 7059): <asynchronous suspension>
E/flutter ( 7059): #2      AndroidFlutterVision.loadYoloModel (package:flutter_vision/src/plugin/android.dart:92:7)
E/flutter ( 7059): <asynchronous suspension>
E/flutter ( 7059): #3      _YoloImageV8SegState.loadYoloModel (package:flutter_vision_example/main.dart:708:5)
E/flutter ( 7059): <asynchronous suspension>
E/flutter ( 7059): #4      _YoloImageV8SegState.initState.<anonymous closure> (package:flutter_vision_example/main.dart:659:26)
E/flutter ( 7059): <asynchronous suspension>
E/flutter ( 7059): 
I/ViewRootImpl@84c701e[MainActivity]( 7059): MSG_WINDOW_FOCUS_CHANGED 0 0

**Comment by XeroDays** [comment]
@chaukamm Export the model with the following parameters 
`model.export(format='tflite', imgsz=640, int8=True)
`
This will generate several tflite files such as 
```
- best_float16.tflite
- best_float32.tflite
- best_int8.tflite
-and many others.
```


But you have to use this one **`best_float16.tflite`**
